### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by reesericci** [valera-rozuvan/jest-expect-standalone#2]
Is this library still being maintained?

**Comment by valera-rozuvan** [comment]
Sorry to inform you, but sadly I don't have the time to maintain this package any longer. I will archive this GitHub repository.

Some more details. I tried to build the latest version of Facebook jest-expect just today. It changed too much, and will require much effort to update the current code base of `jest-expect-standalone` to support it. The `jest-expect-standalone` project simply hasn't been updated in a LOOONG time, and has fallen behind the NPM ecosystem.
